In [3]:
import numpy as np

In [4]:
# Вычислить определители матриц, прорешал на листке

matrix = np.array([
    [4, 0, 4, 5],
    [0, 1, 5, 6],
    [-2, 2, 2, 0],
    [1, -5, 1, 3]
])
d = round(np.linalg.det(matrix))
print(d)

matrix_2 = np.array([
    [5, 0, 1, 3],
    [0, 1, 5, -1],
    [7, -1, 3, -2],
    [5, 3, 0, 1]
])
d = round(np.linalg.det(matrix_2))
print(d)

matrix_3 = np.array([
    [4, 0, 1, 5],
    [1, 1, 0, 4],
    [0, 1, 1, 5],
    [6, -4, 1, 1]
])
d = round(np.linalg.det(matrix_3))
print(d)

matrix_4 = np.array([
    [5, 1, 3, 0],
    [-3, 0, 5, 2],
    [2, 1, -1, 3],
    [1, 5, 0, 7]
])
d = round(np.linalg.det(matrix_4))
print(d)

matrix_5 = np.array([
    [7, 6, 0, 1],
    [1, 3, 5, 0],
    [0, 1, -2, 4],
    [1, 1, 2, 3]
])
d = round(np.linalg.det(matrix_5))
print(d)

matrix_6 = np.array([
    [2, 3, 0, 1],
    [-4, 0, 3, 1],
    [0, 8, 7, 5],
    [3, 3, 4, 5]
])
d = round(np.linalg.det(matrix_6))
print(d)

matrix_7 = np.array([
    [3, 1, 3, 1],
    [2, 4, 2, 5],
    [1, 4, 5, 3],
    [-1, 0, 3, 2]
])
d = round(np.linalg.det(matrix_7))
print(d)

matrix_8 = np.array([
    [7, 6, 0, 1],
    [1, 3, 5, 0],
    [0, 1, -2, 4],
    [1, 1, 2, 3]
])
d = round(np.linalg.det(matrix_8))
print(d)


188
-543
36
408
-288
96
160
-288


In [5]:
# Операции над матрицами, на примере одного варианта

A = np.array([
    [1, 2, 4],
    [7, 5, -2],
    [-2, 1, 3]
])

B = np.array([
    [-1, 0, 3],
    [2, -6, 1],
    [7, 1, 5]
])

C = np.array([
    [-2, 3],
    [4, 0],
    [7, -1]
])

summ = np.add(A, B)
subst = np.subtract(A, B)
multip_ab = np.dot(A, B)
multip_abc = np.dot(multip_ab, C)

print( f'Summ of matrix: \n {summ}')
print(f'Subsctraction: \n {subst}')
print(f'Multiplication A and B Matrix: \n {multip_ab}')
print(f'Multiplication A, B and C Matrix: \n {multip_abc}')

Summ of matrix: 
 [[ 0  2  7]
 [ 9 -1 -1]
 [ 5  2  8]]
Subsctraction: 
 [[ 2  2  1]
 [ 5 11 -3]
 [-9  0 -2]]
Multiplication A and B Matrix: 
 [[ 31  -8  25]
 [-11 -32  16]
 [ 25  -3  10]]
Multiplication A, B and C Matrix: 
 [[ 81  68]
 [  6 -49]
 [  8  65]]


In [ ]:
# Реализация свертки

import matplotlib.pyplot as plt

def convolve2d_manual(image, kernel):
    kernel_height, kernel_width = kernel.shape
    image_height, image_width, num_channels = image.shape

    output = np.zeros((image_height - kernel_height + 1, image_width - kernel_width + 1, num_channels))

    for channel in range(num_channels):
        for y in range(image_height - kernel_height + 1):
            for x in range(image_width - kernel_width + 1):
                output[y, x, channel] = np.sum(
                    image[y:y + kernel_height, x:x + kernel_width, channel] * kernel
                ).clip(0, 255)

    return output.astype(np.uint8)


# Example of a 3x3 convolution kernel
kernel = np.array([[-1, -1, -1],
                   [-1, 10, -1],
                   [-1, -1, -1]])


image = plt.imread('/content/sample_data/Image_4_medium.jpg')
print(image.shape)
print(image)

convolved_image = convolve2d_manual(image, kernel)


plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(image)
plt.title("Original Image")

plt.subplot(1, 2, 2)
plt.imshow(convolved_image)
plt.title("Convolved Image")

plt.show()